export const GET_ERRORS = 'GET_ERRORS';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const PORTFOLIO_CREATE_REQUEST = 'PORTFOLIO_CREATE_REQUEST';
export const PORTFOLIO_CREATE_SUCCESS = 'PORTFOLIO_CREATE_SUCCESS';
export const PORTFOLIO_CREATE_FAIL = 'PORTFOLIO_CREATE_FAIL';
export const PORTFOLIO_All_REQUEST = 'PORTFOLIO_All_REQUEST';
export const PORTFOLIO_All_SUCCESS = 'PORTFOLIO_All_SUCCESS';
export const PORTFOLIO_All_FAIL = 'PORTFOLIO_All_FAIL';
export const PORTFOLIO_DELETE_REQUEST = 'PORTFOLIO_DELETE_REQUEST';
export const PORTFOLIO_DELETE_SUCCESS = 'PORTFOLIO_DELETE_SUCCESS';
export const PORTFOLIO_DELETE_FAIL = 'PORTFOLIO_DELETE_FAIL';
export const PORTFOLIO_VIEW_REQUEST = 'PORTFOLIO_VIEW_REQUEST';
export const PORTFOLIO_VIEW_SUCCESS = 'PORTFOLIO_VIEW_SUCCESS';
export const PORTFOLIO_VIEW_FAIL = 'PORTFOLIO_VIEW_FAIL';
export const PORTFOLIO_VIEW_DELETE = 'PORTFOLIO_VIEW_DELETE';
export const PORTFOLIO_EDIT_DELETE = 'PORTFOLIO_EDIT_DELETE';

export const LANGUAGE_CREATE_REQUEST = 'LANGUAGE_CREATE_REQUEST';
export const LANGUAGE_CREATE_SUCCESS = 'LANGUAGE_CREATE_SUCCESS';
export const LANGUAGE_CREATE_FAIL = 'LANGUAGE_CREATE_FAIL';
export const LANGUAGE_CURRENT_REQUEST = 'LANGUAGE_CURRENT_REQUEST';
export const LANGUAGE_CURRENT_SUCCESS = 'LANGUAGE_CURRENT_SUCCESS';
export const LANGUAGE_CURRENT_FAIL = 'LANGUAGE_CURRENT_FAIL';
export const LANGUAGE_VIEW_REQUEST = 'LANGUAGE_VIEW_REQUEST';
export const LANGUAGE_VIEW_SUCCESS = 'LANGUAGE_VIEW_SUCCESS';
export const LANGUAGE_VIEW_FAIL = 'LANGUAGE_VIEW_FAIL';
export const LANGUAGE_EDIT_REQUEST = 'LANGUAGE_EDIT_REQUEST';
export const LANGUAGE_EDIT_SUCCESS = 'LANGUAGE_EDIT_SUCCESS';
export const LANGUAGE_EDIT_FAIL = 'LANGUAGE_EDIT_FAIL';
export const LANGUAGE_DELETE_REQUEST = 'LANGUAGE_DELETE_REQUEST';
export const LANGUAGE_DELETE_SUCCESS = 'LANGUAGE_DELETE_SUCCESS';
export const LANGUAGE_DELETE_FAIL = 'LANGUAGE_DELETE_FAIL';



///////////////////Message///////////////
export const MSG_COMMON_SUCCESS = 'MSG_COMMON_SUCCESS';
export const MSG_COMMON_FAIL = 'MSG_COMMON_FAIL';
